# Generated by Django 5.0 on 2024-02-13 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_user_count_remove_user_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
