# Generated by Django 5.0 on 2024-02-13 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_profile_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
    ]
