# Generated by Django 5.0 on 2024-02-13 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='times',
            field=models.TextField(blank=True, default=''),
        ),
    ]
