name: Python Code Quality

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  lint_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Set up PostgreSQL database and Python
      run: |
        sudo apt-get update
        sudo apt-get install python3-pip -y
        sudo apt-get install postgresql postgresql-contrib -y
        sudo apt install python3-psycopg2
        sudo apt-get install libpq-dev
        pip install psycopg2-binary
        sudo service postgresql start
        sudo -u postgres psql -c "CREATE DATABASE appdb;"
        sudo -u postgres psql -c "CREATE USER umair WITH PASSWORD 'umair';"
        sudo -u postgres psql -c "ALTER ROLE umair SET client_encoding TO 'utf8';"
        sudo -u postgres psql -c "ALTER ROLE umair SET default_transaction_isolation TO 'read committed';"
        sudo -u postgres psql -c "ALTER ROLE umair SET timezone TO 'UTC';"
        sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE appdb TO umair;"
        sudo service postgresql restart
        sudo -u postgres psql -c "ALTER ROLE umair CREATEDB;"
        sudo service postgresql restart
        
    - name: Install dependencies
      run: |
        pip install flake8 isort django

    - name: Run Flake8
      run: flake8 .

    - name: Run isort
      run: isort .

    - name: Run Django tests
      run: python manage.py test
