name: Python Code Quality

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  lint_and_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2

    - run: |
        pip install flake8 isort
        flake8 .
        isort .

    - name: Run Tests
      run: python manage.py test
