name: Python Code Quality and Test

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  lint_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2


    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - run: |
        pip install flake8 isort
        flake8 .
        isort .

    - name: Run Tests
    - run: |
        pip install django
        python3 manage.py test
